import { CategoryTypes } from "@prisma/client"

export const categories: { name: CategoryTypes; keywords: string[] }[] = [
  { name: "Other", keywords: [] },
  {
    name: "Bills",
    keywords: [
      "bill",
      "bills",
      "utility",
      "utilities",
      "electricity",
      "water",
      "gas",
      "bsnl",
      "jio",
      "airtel",
      "recharge",
      "subscription",
      "subscriptions",
      "maintenance",
      "internet",
      "prepaid",
      "postpaid",
      "telecom",
      "tax",
      "taxes",
      "tv",
      "power",
      "torrent",
      "pgvcl",
      "ugvcl",
      "mgvcl",
      "dgvcl",
      "vera",
      "gst",
      "vodafone idea",
      "vi",
      "dish tv",
      "tata sky",
      "d2h",
      "lpg",
      "cylinder",
    ],
  },
  {
    name: "Food",
    keywords: [
      "food",
      "restaurant",
      "meal",
      "dinner",
      "lunch",
      "breakfast",
      "zomato",
      "swiggy",
      "cafe",
      "dhaba",
      "manchurian",
      "kfc",
      "pizza",
      "burger",
      "pasta",
      "ice cream",
      "coffee",
      "tea",
      "samosa",
      "momo",
      "biryani",
      "dosa",
      "dhosa",
      "snack",
      "chips",
      "chocolate",
      "fries",
      "snacks",
      "salad",
      "fast food",
      "delivery",
      "sushi",
      "curry",
      "jalebi",
      "sandwich",
      "dessert",
      "noodles",
      "sweets",
      "biscuit",
      "rice",
      "gathiya",
      "khaman",
      "khamman",
      "locho",
      "punjabi",
      "chinese",
      "subway",
      "bhajiya",
      "vada",
      "idli",
      "thali",
      "dabeli",
      "vadapav",
      "pani puri",
      "sev",
      "fafda",
      "dhokla",
      "undhiyu",
      "khandvi",
      "dal dhokli",
      "farsan",
      "thepla",
      "rotli",
      "chai",
      "lassi",
      "buttermilk",
      "chaas",
      "pav bhaji",
      "gujarati",
      "kathiyawadi",
      "surti",
    ],
  },
  {
    name: "Entertainment",
    keywords: [
      "movie",
      "movies",
      "concert",
      "game",
      "parties",
      "party",
      "theatre",
      "theater",
      "show",
      "pvr",
      "inox",
      "netflix",
      "prime",
      "hotstar",
      "picture",
      "music",
      "radio",
      "cinema",
      "esport",
      "prime",
      "zee5",
      "sony",
      "premiere",
      "party",
      "ramzat",
      "club",
      "park",
      "dj",
      "imax",
      "garba",
      "dandiya",
      "navratri",
      "kite festival",
      "uttarayan",
      "amusement park",
      "water park",
      "museum",
      "multiplex",
      "bookmyshow",
      "jio cinema",
      "voot",
      "alt balaji",
      "mxplayer",
    ],
  },
  {
    name: "Transportation",
    keywords: [
      "bus",
      "train",
      "taxi",
      "uber",
      "ola",
      "fare",
      "auto",
      "metro",
      "rickshaw",
      "cab",
      "flight",
      "aeroplane",
      "ferry",
      "cruise",
      "toll",
      "fastag",
      "brts",
      "amts",
      "gsrtc",
      "rapido",
      "jugnoo",
      "irctc",
      "makemytrip",
      "goibibo",
      "redbus",
      "zoomcar",
      "revv",
      "yulu",
      "vogo",
      "parking",
    ],
  },
  {
    name: "EMI",
    keywords: [
      "emi",
      "loan",
      "installment",
      "payment",
      "bajaj",
      "hdfc",
      "sbi",
      "kotak",
      "icici",
      "axis",
      "paytm",
      "debt",
      "interest",
      "bank",
      "card",
      "lender",
      "borrow",
      "idbi",
      "rbi",
      "mortgage",
      "credit card",
      "overdraft",
      "gpay",
      "phonepe",
      "bhim",
    ],
  },
  {
    name: "Healthcare",
    keywords: [
      "doctor",
      "hospital",
      "medicine",
      "pharmacy",
      "health",
      "apollo",
      "fortis",
      "operation",
      "clinic",
      "dentist",
      "eye",
      "dava",
      "laboratory",
      "insurance",
      "therapy",
      "vaccine",
      "prescription",
      "checkup",
      "consultation",
      "icu",
      "surgery",
      "xray",
      "scan",
      "mri",
      "healthcare",
      "treatment",
      "civil",
      "sterling",
      "zydus",
      "shalby",
      "cims",
      "ayurveda",
      "homeopathy",
      "yoga",
      "physiotherapy",
      "optician",
      "pathology",
      "blood",
      "aarogyasetu",
      "wellness",
      "sanjeevani",
    ],
  },
  {
    name: "Education",
    keywords: [
      "school",
      "college",
      "course",
      "book",
      "tuition",
      "study",
      "tution",
      "unacademy",
      "academy",
      "udemy",
      "learn",
      "coursera",
      "university",
      "exam",
      "degree",
      "diploma",
      "class",
      "training",
      "certification",
      "textbook",
      "chopda",
      "library",
      "iim",
      "nit",
      "iit",
      "iiit",
      "gtu",
      "nirma",
      "pdpu",
      "charusat",
      "coaching",
      "byju",
      "vedantu",
      "toppr",
      "nptel",
      "swayam",
      "upsc",
      "gpsc",
      "ielts",
      "toefl",
      "gre",
      "gmat",
    ],
  },
  {
    name: "Investment",
    keywords: [
      "invest",
      "stock",
      "bond",
      "mutual fund",
      "crypto",
      "sip",
      "lic",
      "nsc",
      "ppf",
      "ipo",
      "zerodha",
      "upstox",
      "groww",
      "angel",
      "motilal oswal",
      "icici direct",
      "nse",
      "bse",
      "sensex",
      "nifty",
      "demat",
      "trading",
      "dividend",
      "gold",
      "silver",
      "etf",
      "elss",
      "nps",
      "fixed deposit",
      "fd",
      "recurring deposit",
      "rd",
    ],
  },
  {
    name: "Shopping",
    keywords: [
      "shop",
      "mall",
      "clothes",
      "accessories",
      "flipkart",
      "amazon",
      "myntra",
      "laptop",
      "mobile",
      "electronics",
      "fashion",
      "footwear",
      "appliance",
      "e-commerce",
      "purchase",
      "jewellery",
      "makeup",
      "beauty",
      "store",
      "shirt",
      "tshirt",
      "jeans",
      "kurti",
      "ajio",
      "nykaa",
      "snapdeal",
      "meesho",
      "reliance digital",
      "croma",
      "vijay sales",
      "tanishq",
      "kalyan",
      "tbz",
      "lifestyle",
      "westside",
      "pantaloons",
      "saree",
      "fabindia",
      "bandhani",
      "patola",
      "chaniya choli",
      "zudio",
    ],
  },
  {
    name: "Fuel",
    keywords: [
      "gas",
      "petrol",
      "diesel",
      "fuel",
      "cng",
      "indian oil",
      "hp",
      "petroleum",
      "essar",
      "charging",
      "charge",
      "ev",
      "electric vehicle",
      "pump",
    ],
  },
  {
    name: "Groceries",
    keywords: [
      "grocery",
      "supermarket",
      "market",
      "bigbasket",
      "dmart",
      "vegetable",
      "fruits",
      "vegetables",
      "fruit",
      "ration",
      "flour",
      "grain",
      "reliance fresh",
      "jiomart",
      "apmc",
      "sabji",
      "kirana",
      "provison",
      "bazar",
      "spice",
      "masala",
      "oil",
      "ghee",
      "dairy",
      "amul",
      "pulse",
      "dal",
      "rice",
      "atta",
      "salt",
      "sugar",
    ],
  },
]
