name: Keep API Alive

on:
  schedule:
    # This will run every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
    - name: Call API
      run: |
        curl -X GET 'https://your-api-endpoint.com'
