name: Keep API Alive
on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:  
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
    - name: Call API
      env:
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      run: |
        curl -X GET $API_ENDPOINT
