name: Trigger Deploy Commit

on:
  push:
    branches:
      - main # Change if needed

jobs:
  deploy_trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }} # Use PAT for write access

      - name: Configure Git
        run: |
          git config --global user.name "Project-Group-SGP"
          git config --global user.email "etracker690@gmail.com"

      - name: Prepend newline to global.d.ts
        run: |
          sed -i '1s/^/\n/' global.d.ts

      - name: Commit and Push Changes
        if: github.event.head_commit.message != 'Trigger deploy by adding a newline'
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git add .
          git commit -m "Trigger deploy by adding a newline"
          git push origin main
